name: 'Pull request reviews reminder action'
description: 'Automatically send notification for pull requests waiting for reviewers'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  open-time:
    description: ''
    required: false
    default: ''
  webhook-url: 
    description: 'Slack Webhook URL'
    required: true
  channel:
    description: 'Slack Channel name'
    required: false
    default: '#general'
runs:
  using: 'node20'
  main: 'dist/index.js'

