name: 'Pull request reviews reminder action'
description: 'Automatically send notification for pull requests waiting for reviewers'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  pr-last-updated-time-exceeding-x-hours: # optional
    description: 'fetch Pull Requests with last updated time exceeding X hours'
    required: false
    default: '0' # default get all open Pull Requests
  slack-channel-name: 
    description: 'Slack Channel name'
    required: true
    default: '#general'
  slack-webhook-url:  #  only if no slack token
    description: 'Slack Webhook URL'
    required: false
  ai-language:
    description: 'lang'
    required: false
    default: 'en'

runs:
  using: 'node20'
  main: 'dist/index.js'

