name: 'Pull request reviews reminder action'
description: 'Automatically send notification for pull requests waiting for reviewers'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  open-time:
    description: ''
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'

