name: 'Pull request reviews reminder action'
description: 'Automatically send notification for pull requests waiting for reviewers'
branding:
  icon: 'bell'
  color: 'red'
inputs:
  NOTIFY_WHEN_PR_LAST_UPDATED_TIME_EXCEEDING_X_HOURS: # optional
    description: 'fetch Pull Requests with last updated time exceeding X hours'
    required: false
    default: '0'
  SLACK_CHANNEL_ID: 
    description: 'Slack Channel ID (e.g: C04XU9CXKA4)'
    required: false
  LANG:
    description: 'language'
    required: false
    default: 'en'
  SLACK_WEBHOOK_URL_CHANNEL_NAME: 
    description: 'Slack Channel name'
    required: false
    default: '#general'
  SLACK_WEBHOOK_URL: 
    description: 'Slack Webhook URL'
    required: false


runs:
  using: 'node20'
  main: 'dist/index.js'

